sudo: false

dist: trusty

addons:
  apt:
    packages:
    - oracle-java8-installer

git:
  depth: 50

language: php

cache:
  apt: true

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly


before_install:
  # Update Composer
  - composer self-update
  # Disable xdebug
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then phpenv config-rm xdebug.ini; fi;

install:
  # Update dependencies
  - composer install --quiet --no-interaction --prefer-dist
  - composer dumpautoload -o

script:
  # Run PHPUnit
  - bin/phpunit
